#!/usr/bin/env python3
"""Sync infrastructure/.env from Vault.

Reads per-agent OR keys from `secret/hermes/openrouter-api-keys` and
Discord bot tokens from `secret/hermes/<agent>/discord-bot-token-*`,
writes them to infrastructure/.env in the format docker-compose expects.

Used by humans (post-Vault rotation) and by cron health checks (to
detect drift between Vault and compose-time env).

Usage:
    python3 sync-env-from-vault.py          # write .env from Vault
    python3 sync-env-from-vault.py --check  # exit 0 if .env matches Vault, 1 if drift
"""
import argparse
import json
import os
import sys
import urllib.request

VAULT_ADDR = "https://vault.vps.dttesting.com"
OR_KEYS_PATH = "hermes/openrouter-api-keys"

# Map: compose var name -> (Vault field name in OR_KEYS_PATH, agent dir)
AGENT_OR_KEYS = [
    ("OPENROUTER_API_KEY_ZEPHYR",       "zephyr"),
    ("OPENROUTER_API_KEY_PHOENIX",      "phoenix"),
    ("OPENROUTER_API_KEY_ORBIT",        "orbit"),
    ("OPENROUTER_API_KEY_PM",           "project-manager"),
    ("OPENROUTER_API_KEY_REVIEWER",     "code-reviewer"),
    ("OPENROUTER_API_KEY_RESEARCHER",   "researcher"),
    ("OPENROUTER_API_KEY_WRITER",       "technical-writer"),
    ("OPENROUTER_API_KEY_KHAOS",        "khaos"),
]

# Discord tokens: agent -> vault path
DISCORD_TOKENS = {
    "DISCORD_BOT_TOKEN_ZEPHYR": "hermes/zephyr/discord-bot-token-zephyr-openclaw",
    "DISCORD_BOT_TOKEN_ORBIT":  "hermes/orbit/discord-bot-token-orbit",
}


def get_approle_token(env_file: str = os.path.expanduser("~/.hermes/.env")) -> str:
    env = {}
    with open(env_file) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k] = v
    role_id = env["VAULT_ROLE_ID"]
    secret_id = env["VAULT_SECRET_ID"]
    data = json.dumps({"role_id": role_id, "secret_id": secret_id}).encode()
    req = urllib.request.Request(
        f"{VAULT_ADDR}/v1/auth/approle/login",
        data=data,
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read())["auth"]["client_token"]


def vault_read(token: str, path: str) -> dict:
    req = urllib.request.Request(
        f"{VAULT_ADDR}/v1/secret/data/{path}",
        headers={"X-Vault-Token": token},
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read())["data"]["data"]


# Open-Brain MCP access keys (per-agent isolated Supabase tables)
BRAIN_KEYS = {
    "OPEN_BRAIN_KEY_KHAOS": "paperclip/services/khaos-brain-supabase",
}

def collect(token: str) -> dict:
    """Return {env_var_name: value} ready for .env file."""
    or_keys = vault_read(token, OR_KEYS_PATH)
    out = {}
    for env_var, vault_field in AGENT_OR_KEYS:
        if vault_field not in or_keys:
            sys.exit(f"ERROR: Vault field '{vault_field}' missing at {OR_KEYS_PATH}")
        out[env_var] = or_keys[vault_field]
    for env_var, vault_path in DISCORD_TOKENS.items():
        d = vault_read(token, vault_path)
        # Inconsistent naming across entries — accept either "token" or "Token"
        tok = d.get("token") or d.get("Token")
        if not tok:
            sys.exit(f"ERROR: no token field at {vault_path} (looked for 'token' and 'Token')")
        out[env_var] = tok
    for env_var, vault_path in BRAIN_KEYS.items():
        d = vault_read(token, vault_path)
        brain_key = d.get("mcp-access-key")
        if not brain_key:
            sys.exit(f"ERROR: no mcp-access-key at {vault_path}")
        out[env_var] = brain_key
    return out


def render_env(values: dict) -> str:
    lines = [
        "# Auto-generated by sync-env-from-vault.py — DO NOT EDIT BY HAND.",
        "# Source of truth: Vault (secret/hermes/openrouter-api-keys + discord-bot-token-*)",
        "# Regenerate with: python3 infrastructure/scripts/sync-env-from-vault.py",
        "",
    ]
    for env_var, vault_field in AGENT_OR_KEYS:
        lines.append(f"# {vault_field} OR key from Vault field '{vault_field}'")
        lines.append(f"{env_var}={values[env_var]}")
    lines.append("")
    for env_var, vault_path in DISCORD_TOKENS.items():
        lines.append(f"# Discord bot token from Vault path '{vault_path}'")
        lines.append(f"{env_var}={values[env_var]}")
    lines.append("")
    for env_var, vault_path in BRAIN_KEYS.items():
        lines.append(f"# Open-Brain MCP key from Vault path '{vault_path}'")
        lines.append(f"{env_var}={values[env_var]}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="Exit 0 if .env matches Vault, 1 if drift")
    parser.add_argument("--out", default="infrastructure/.env",
                        help="Output .env path (relative to repo root)")
    args = parser.parse_args()

    repo_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    out_path = os.path.join(repo_root, args.out)

    token = get_approle_token()
    values = collect(token)
    new_content = render_env(values)

    if args.check:
        if not os.path.exists(out_path):
            print(f"DRIFT: {out_path} missing")
            sys.exit(1)
        existing = open(out_path).read()
        if existing.strip() != new_content.strip():
            print(f"DRIFT: {out_path} differs from Vault")
            sys.exit(1)
        print(f"OK: {out_path} matches Vault")
        return

    with open(out_path, "w") as f:
        f.write(new_content)
    os.chmod(out_path, 0o600)
    print(f"Wrote {len(values)} secrets to {out_path} (mode 600)")


if __name__ == "__main__":
    main()